### PR TITLE
Menu entry for weather refresh rate

### PR DESCRIPTION
**Pull request by untergrundbiber**

### CODE REVIEW

**Comment by pixbox-hdf** [comment]
we have default 60 minutes

**Comment by untergrundbiber** [comment]
It should remain so, but you can give the user even the possibility to change it

**Comment by koivo** [comment]
We want to have the configuration for Xion at one side.
We discuss this and we think nobody needs a weather refresh Time of 5min.
60 minutes is a good way in the middle.

**Comment by untergrundbiber** [comment]
Ok then I'll have to continue edit my config manually

**Pull request closed without merging**
